In [6]:
import tensorflow as tf
graph = tf.Graph()
with graph.as_default():
  variable = tf.Variable(42, name='foo')
#   initialize = tf.global_variables_initializer()
  assign = variable.assign(13)


AttributeError: module 'tensorflow' has no attribute 'global_variables_initializer'

In [7]:
with tf.Session(graph=graph) as sess:
#   sess.run(initialize)
  sess.run(assign)
  print(sess.run(variable))

AttributeError: module 'tensorflow' has no attribute 'Session'

In [8]:
import tensorflow as tf  
x = tf.constant([2.0], dtype = tf.float32)
print(tf.sqrt(x))

tf.Tensor([1.4142135], shape=(1,), dtype=float32)


In [12]:
import tensorflow as tf 
x = tf.constant([[2]], dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor([[1.4142135]], shape=(1, 1), dtype=float32)


In [15]:
tensor_a = tf.constant([[1,2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)
tensor_add = tf.add(tensor_a, tensor_b)
print(tensor_add)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


In [4]:
import tensorflow as tf
c = tf.constant(2.0,tf.float32)
d = tf.constant(3.0)
print(c,d)

tf.Tensor(2.0, shape=(), dtype=float32) tf.Tensor(3.0, shape=(), dtype=float32)


In [6]:
import tensorflow as tf 
Y = tf.Variable([.4],dtype=tf.float32)
a = tf.Variable([-.4],dtype=tf.float32)
b = tf.placeholder(tf.float32)
linear_model = Y*b+a


AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [20]:
import tensorflow as tf 
# creating nodes in computation graph
node1 = tf.constant(3, dtype=tf.int32)
node2 = tf.constant(5, dtype=tf.int32)
node3 = tf.add(node1, node2)
 
# create tensorflow session object
sess = tf.compat.v1.Session()
 
# evaluating node3 and printing the result
print("sum of node1 and node2 is :",sess.run(node3))
# closing the session
sess.close()

RuntimeError: The Session graph is empty. Add operations to the graph before calling run().

In [7]:
# importing tensorflow
import tensorflow as tf
 
# creating nodes in computation graph
node = tf.Variable(tf.zeros([2,2]))
 
# running computation graph
with tf.Session() as sess:
 
    # initialize all global variables
    sess.run(tf.global_variables_initializer())
 
    # evaluating node
    print("Tensor value before addition:\n",sess.run(node))
 
    # elementwise addition to tensor
    node = node.assign(node + tf.ones([2,2]))
 
    # evaluate node again
    print("Tensor value after addition:\n", sess.run(node))

AttributeError: module 'tensorflow' has no attribute 'Session'