In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [1]:
#2d array in numerical python
import numpy as np
a = np.array([[1,2],[5,6]])
print(a)


[[1 2]
 [5 6]]


In [5]:
#3d array
import numpy as np
arr = np.array([[[1,2,3],[3,4,5]],[[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [3 4 5]]

 [[4 5 6]
  [7 8 9]]]


In [8]:
#5d array
import numpy as np
arr = np.array([1,2,3,4],ndmin=10)
print(arr)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


In [10]:
#how to check dimensions of an array
import numpy as np
a=np.array([[1,2,3,4,5]])
b=np.array(42)
print(a.ndim)
print(b.ndim)

2
0


In [13]:
#checking of shape of array
import numpy as np
arr1=np.array([1,3,5,7,8,9])
print(arr1.shape)

(6,)


In [14]:
#matrix operations helping fn
import numpy as np
np.zeros(4)

array([0., 0., 0., 0.])

In [15]:
import numpy as np
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
import numpy as np
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [18]:
#sorting arrays
import numpy as np
arr = np.array([8,9,56,23,14,100,49,1,63,155,200])
np.sort(arr)

array([  1,   8,   9,  14,  23,  49,  56,  63, 100, 155, 200])

In [19]:
#sorting alphabetical data
import numpy as np
arr = np.array(['banana','apple','mango','grapes'])
np.sort(arr)

array(['apple', 'banana', 'grapes', 'mango'], dtype='<U6')

In [24]:
#access array elements
import numpy as np
arr = np.array([1,2,3,4,5,6,7,58,98,100])
print(arr[0])
print(arr[0:8])
print(arr[:5])
print(arr[3:])
print(arr[:-2])


1
[ 1  2  3  4  5  6  7 58]
[1 2 3 4 5]
[  4   5   6   7  58  98 100]
[ 1  2  3  4  5  6  7 58]


In [29]:
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,87,23]])
print('2nd element on 1st row : ',arr[0,1])

2nd element on 1st row :  2


In [35]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[0:5:4])

[10 50]


In [41]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,3:5])

[4 5]


In [43]:
#searching in an array by 2 methods
import numpy as np
arr = np.array([1,2,10,4,10,10,8,9,10])
x=np.where(arr == 10)
print(x)


(array([2, 4, 5, 8], dtype=int64),)


In [44]:
import numpy as np
arr = np.array([1,2,10,4,10,10,8,9,10])
x=np.where(arr % 2 == 0)
print(x)


(array([1, 2, 3, 4, 5, 6, 8], dtype=int64),)


In [45]:
import numpy as np
arr = np.array([1,2,10,4,10,10,8,9,10])
print(len(list(arr)))


9


In [3]:
#serchsorted method
import numpy as np
arr = np.array([500,8,91,10,56,45,125,51])
x=np.searchsorted(arr,15)
print(x)

2


In [5]:
#reshape of array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
#convert array into 1D array
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr = arr.reshape(-1)
print(newarr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [10]:
#filtering array
import numpy as np
arr = np.array([41,42,43,44])
x = [True,False,True,False]
newarr= arr[x]
print(newarr)

[41 43]


In [14]:
#sequence of array
seq = [0,1,2,3,5,8,13]
result = filter(lambda x : x % 2 != 0,seq)
print(list(result))

[1, 3, 5, 13]


In [15]:
#concatination
a=np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [16]:
b=np.arange(7,13).reshape(2,3)
print(b)

[[ 7  8  9]
 [10 11 12]]


In [17]:
np.concatenate((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.stack((a,b))


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
np.hstack((a,b))


array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [22]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
np.dstack((a,b))

array([[[ 0,  7],
        [ 1,  8],
        [ 2,  9]],

       [[ 3, 10],
        [ 4, 11],
        [ 5, 12]]])